services:
    - docker

env:
  global:
    - ON_TRAVIS=true
    # - IMAGE=elpaso/qgis-testing-environment
    # - IMAGE=boundlessgeo/qgis-testing-environment
    - IMAGE=kartoza/qgis-testing

  matrix:
    # Tags from elpaso
    # - QGIS_VERSION_TAG=release-2_8
    # - QGIS_VERSION_TAG=release-2_14

    # Tags from boundlessgeo
    # - QGIS_VERSION_TAG=release # Current 2.14
    # - QGIS_VERSION_TAG=master_2 # Current 2.17
    # - QGIS_VERSION_TAG=master # Current 3.0

    # Tags from kartoza
    - QGIS_VERSION_TAG=boundlessgeo-2.14.7

language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

virtualenv:
  system_site_packages: true

branches:
  only:
    - master
    - develop
    - experimental

addons:
  apt:
    packages:
      - git
      - python-software-properties

before_install:
  - docker pull ${IMAGE}:${QGIS_VERSION_TAG}

install:
  - pip install --upgrade pip
  - pip install --upgrade pep8
  - echo ${TRAVIS_BUILD_DIR}
  - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e ON_TRAVIS=${ON_TRAVIS} -e DISPLAY=:99 ${IMAGE}:${QGIS_VERSION_TAG}
  - sleep 10
  - docker exec -it qgis-testing-environment sh -c "qgis_setup.sh GeoHealth"
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - export PYTHONPATH=$PYTHONPATH:$(dirname "$(pwd)")
  - echo $PYTHONPATH
  - docker exec -it  qgis-testing-environment sh -c "ln -s /tests_directory /root/.qgis2/python/plugins/GeoHealth"

script:
  - make pep8
  - docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh test_suite.test_package"
  - docker exec -it qgis-testing-environment sh -c "echo $PYTHONPATH"

notifications:
  email:
    - etienne.trimaille@gmail.com

sudo: false
