# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/incidence.ui'
#
# Created: Sat Nov  8 11:42:54 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Incidence(object):
    def setupUi(self, Incidence):
        Incidence.setObjectName(_fromUtf8("Incidence"))
        Incidence.resize(634, 554)
        self.verticalLayout = QtGui.QVBoxLayout(Incidence)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.messageBar = gui.QgsMessageBar(Incidence)
        self.messageBar.setObjectName(_fromUtf8("messageBar"))
        self.verticalLayout.addWidget(self.messageBar)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_4 = QtGui.QLabel(Incidence)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.comboBox_incidence_pointLayer = QtGui.QComboBox(Incidence)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_incidence_pointLayer.sizePolicy().hasHeightForWidth())
        self.comboBox_incidence_pointLayer.setSizePolicy(sizePolicy)
        self.comboBox_incidence_pointLayer.setObjectName(_fromUtf8("comboBox_incidence_pointLayer"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_incidence_pointLayer)
        self.label = QtGui.QLabel(Incidence)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.comboBox_incidence_adminLayer = QtGui.QComboBox(Incidence)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_incidence_adminLayer.sizePolicy().hasHeightForWidth())
        self.comboBox_incidence_adminLayer.setSizePolicy(sizePolicy)
        self.comboBox_incidence_adminLayer.setObjectName(_fromUtf8("comboBox_incidence_adminLayer"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox_incidence_adminLayer)
        self.label_3 = QtGui.QLabel(Incidence)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_incidence_columnName = QtGui.QLineEdit(Incidence)
        self.lineEdit_incidence_columnName.setText(_fromUtf8("incidence"))
        self.lineEdit_incidence_columnName.setObjectName(_fromUtf8("lineEdit_incidence_columnName"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_incidence_columnName)
        self.label_2 = QtGui.QLabel(Incidence)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_2)
        self.comboBox_incidence_ratio = QtGui.QComboBox(Incidence)
        self.comboBox_incidence_ratio.setEditable(True)
        self.comboBox_incidence_ratio.setObjectName(_fromUtf8("comboBox_incidence_ratio"))
        self.comboBox_incidence_ratio.addItem(_fromUtf8(""))
        self.comboBox_incidence_ratio.addItem(_fromUtf8(""))
        self.comboBox_incidence_ratio.addItem(_fromUtf8(""))
        self.comboBox_incidence_ratio.addItem(_fromUtf8(""))
        self.comboBox_incidence_ratio.addItem(_fromUtf8(""))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.comboBox_incidence_ratio)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioButton_incidence_population = QtGui.QRadioButton(Incidence)
        self.radioButton_incidence_population.setChecked(True)
        self.radioButton_incidence_population.setObjectName(_fromUtf8("radioButton_incidence_population"))
        self.horizontalLayout.addWidget(self.radioButton_incidence_population)
        self.comboBox_incidence_populationField = QtGui.QComboBox(Incidence)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_incidence_populationField.sizePolicy().hasHeightForWidth())
        self.comboBox_incidence_populationField.setSizePolicy(sizePolicy)
        self.comboBox_incidence_populationField.setObjectName(_fromUtf8("comboBox_incidence_populationField"))
        self.horizontalLayout.addWidget(self.comboBox_incidence_populationField)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.radioButton_incidence_area = QtGui.QRadioButton(Incidence)
        self.radioButton_incidence_area.setChecked(False)
        self.radioButton_incidence_area.setObjectName(_fromUtf8("radioButton_incidence_area"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.radioButton_incidence_area)
        self.checkBox_addNbIntersections = QtGui.QCheckBox(Incidence)
        self.checkBox_addNbIntersections.setObjectName(_fromUtf8("checkBox_addNbIntersections"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.checkBox_addNbIntersections)
        self.checkBox_incidence_runStats = QtGui.QCheckBox(Incidence)
        self.checkBox_incidence_runStats.setChecked(True)
        self.checkBox_incidence_runStats.setObjectName(_fromUtf8("checkBox_incidence_runStats"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.checkBox_incidence_runStats)
        self.label_6 = QtGui.QLabel(Incidence)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_5 = QtGui.QLabel(Incidence)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.label_5)
        self.label_7 = QtGui.QLabel(Incidence)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(Incidence)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.label_8)
        self.verticalLayout.addLayout(self.formLayout)
        self.button_box_ok = QtGui.QDialogButtonBox(Incidence)
        self.button_box_ok.setOrientation(QtCore.Qt.Horizontal)
        self.button_box_ok.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_box_ok.setObjectName(_fromUtf8("button_box_ok"))
        self.verticalLayout.addWidget(self.button_box_ok)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tableWidget = QtGui.QTableWidget(Incidence)
        self.tableWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.layout_plot = QtGui.QVBoxLayout()
        self.layout_plot.setObjectName(_fromUtf8("layout_plot"))
        self.horizontalLayout_2.addLayout(self.layout_plot)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Incidence)
        self.comboBox_incidence_ratio.setCurrentIndex(4)
        QtCore.QObject.connect(self.radioButton_incidence_population, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboBox_incidence_populationField.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Incidence)

    def retranslateUi(self, Incidence):
        Incidence.setWindowTitle(_translate("Incidence", "Incidence - Density", None))
        self.label_4.setText(_translate("Incidence", "Case layer", None))
        self.label.setText(_translate("Incidence", "Layer for aggregation", None))
        self.label_3.setText(_translate("Incidence", "New column", None))
        self.label_2.setText(_translate("Incidence", "Ratio", None))
        self.comboBox_incidence_ratio.setItemText(0, _translate("Incidence", "10", None))
        self.comboBox_incidence_ratio.setItemText(1, _translate("Incidence", "100", None))
        self.comboBox_incidence_ratio.setItemText(2, _translate("Incidence", "1 000", None))
        self.comboBox_incidence_ratio.setItemText(3, _translate("Incidence", "10 000", None))
        self.comboBox_incidence_ratio.setItemText(4, _translate("Incidence", "100 000", None))
        self.radioButton_incidence_population.setText(_translate("Incidence", "Column population", None))
        self.radioButton_incidence_area.setText(_translate("Incidence", "Area (density)", None))
        self.checkBox_addNbIntersections.setText(_translate("Incidence", "Add the number of cases per unit to the attribute table", None))
        self.checkBox_incidence_runStats.setText(_translate("Incidence", "Calculate statistics", None))
        self.label_6.setText(_translate("Incidence", "<html><head/><body><p><span style=\" font-style:italic;\">Incidence =</span></p></body></html>", None))
        self.label_5.setText(_translate("Incidence", "<html><head/><body><p><span style=\" font-style:italic;\">number of cases / population * ratio</span></p></body></html>", None))
        self.label_7.setText(_translate("Incidence", "<html><head/><body><p><span style=\" font-style:italic;\">Density =</span></p></body></html>", None))
        self.label_8.setText(_translate("Incidence", "<html><head/><body><p><span style=\" font-style:italic;\">number of cases / area * ratio</span></p></body></html>", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Incidence", "Parameter", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Incidence", "Value", None))

from qgis import gui
